### ISSUE TITLE
Обнаружена ошибка при обработке /home/hasher/.vimrc:

### ISSUE THREAD

**Issue by myromeu** [Bashka/vim_lib#2]
.vimrc скопировал с вашей инструкции, но

```
Обнаружена ошибка при обработке /home/hasher/.vimrc:
строка    3:
E117: Неизвестная функция: vim_lib#sys#Autoload#init
строка    5:
E492: Это не команда редактора: Plugin 'vim_lib'

```

**Comment by Bashka** [comment]
А как производится установка библиотеки? То есть по адресу ~/.vim/bundle/vim_lib находится библиотека?

**Comment by myromeu** [comment]
Установил zip-архивом с github.
Да, в ~/.vim/bundle/vim_lib находятся три папки base, sys, view.

**Comment by Bashka** [comment]
В ~/.vim/bundle/vim_lib должно быть три папки autoload, doc и syntax.
Другими словами должно получиться то же, что при выполнении команды 
git clone https://github.com/Bashka/vim_lib.git ~/.vim/bundle/vim_lib

**Comment by myromeu** [comment]
Понял. А я то doc и syntax раскидал по vim'овским папкам..

**Comment by Bashka** [comment]
Это делать не нужно. Автозагрузка так устроена, что все файлы плагина можно хранить в его каталоге и они будут работать без проблем. Это делает каталог .vim более структурированным, так как все плагины хранятся в своих каталогах.

Важно только при добавлении нового плагина (нового каталога в ~/.vim/bundle) прописывать его имя в .vimrc в виде команды Plugin 'имя' перед filetype indent plugin on. На пример:

filetype off
set rtp=~/.vim/bundle/vim_lib
call vim_lib#sys#Autoload#init('~/.vim', 'bundle')

Plugin 'vim_lib'
Plugin 'UltiSnips'
Plugin 'myPlugin'

filetype indent plugin on

**Comment by myromeu** [comment]
Извиняюсь за глупую ошибку. Правильно ли я понял что все ваши плагины нужно держать в папке ~/.vim/bundle/vim_lib ?

**Comment by Bashka** [comment]
Нет, плагины нужно держать в каталоге ~/.vim/bundle. На пример, при установке плагина MyPlugin, он должен хранится в каталоге ~/.vim/bundle/MyPlugin.
vim_lib это не более чем библиотека.

**Comment by myromeu** [comment]
Ок. Именно так изначально и подумал, но смутил предыдущий ваш ответ.
Очень интересный проект. Спасибо вам)

**Comment by Bashka** [comment]
Пожалуйста.

Посоветую вам сделать следующую структуру. В .vimrc добавить запись:

filetype off
set rtp=~/.vim/bundle/vim_lib
call vim_lib#sys#Autoload#init('~/.vim', 'bundle')
so ~/.vim/plugins.vim
filetype indent plugin on

а так же создать файл ~/.vim/plugins.vim в который вы будете добавлять информацию о новых плагинах:

Plugin 'vim_lib'
Plugin 'myPlugin'
...

Вам так будет проще и не придется засорять .vimrc файл.

Так же гляньте на vim_plugmanager, он делает все вышеперечисленное автоматически, использует ~/.vim/plugins.vim файл и самостоятельно добавляет в него команду Plugin.

**Comment by myromeu** [comment]
Хорошо. Так и сделаю.
